# Generated by Django 3.2.16 on 2022-11-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome do recurso')),
                ('descricao', models.CharField(max_length=254, verbose_name='Descrição')),
                ('quantidade', models.IntegerField(max_length=4, verbose_name='Quantidade')),
            ],
        ),
    ]
