# Generated by Django 3.2.16 on 2022-11-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurso',
            options={'ordering': ['nome'], 'verbose_name': 'Recurso', 'verbose_name_plural': 'Recursos'},
        ),
        migrations.AlterField(
            model_name='recurso',
            name='quantidade',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
    ]
