# Generated by Django 3.2.16 on 2022-11-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0002_auto_20221126_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='descricao',
            field=models.TextField(max_length=254, verbose_name='Descrição'),
        ),
    ]
