# Generated by Django 3.2.16 on 2022-11-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0003_alter_recurso_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='descricao',
            field=models.TextField(blank=True, max_length=254, null=True, verbose_name='Descrição'),
        ),
    ]
