# Generated by Django 3.2.16 on 2022-11-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formato_Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Formato da atividade')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome Completo')),
                ('matricula', models.CharField(max_length=13, verbose_name='Matrícula do Estudante')),
                ('email', models.CharField(blank=True, max_length=254, verbose_name='Email')),
                ('celular', models.CharField(blank=True, max_length=14, verbose_name='Número de celular')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Tipo de atividade')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64, verbose_name='Título da atividade')),
                ('descricao', models.TextField(max_length=512, verbose_name='Descrição da apresentação')),
                ('duracao', models.IntegerField(max_length=4, verbose_name='Duração em minutos')),
                ('participantes', models.ManyToManyField(to='participante.Participante')),
                ('recursos', models.ManyToManyField(to='organizacao.Recurso')),
            ],
        ),
    ]
