# Generated by Django 3.2.16 on 2022-11-26 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividade',
            options={'ordering': ['titulo'], 'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
        migrations.AlterModelOptions(
            name='formato_atividade',
            options={'ordering': ['nome'], 'verbose_name': 'Formato de atividade', 'verbose_name_plural': 'Formatos de atividade'},
        ),
        migrations.AlterModelOptions(
            name='participante',
            options={'ordering': ['nome'], 'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes'},
        ),
        migrations.AlterModelOptions(
            name='tipo_atividade',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo de atividade', 'verbose_name_plural': 'Tipos de atividade'},
        ),
        migrations.AddField(
            model_name='atividade',
            name='formato_atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participante.formato_atividade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='tipo_atividade',
            field=models.ManyToManyField(to='participante.Tipo_Atividade'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='duracao',
            field=models.IntegerField(verbose_name='Duração em minutos'),
        ),
    ]
