# Generated by Django 3.2.16 on 2022-11-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0003_rename_tipo_atividade_atividade_tipos_atividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='em_grupo',
            field=models.BooleanField(default=False, verbose_name='A atividade é em grupo?'),
        ),
    ]
