# Generated by Django 3.2.16 on 2022-11-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0004_atividade_em_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='titulo',
            field=models.CharField(max_length=64, unique=True, verbose_name='Título da atividade'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='celular',
            field=models.CharField(max_length=14, verbose_name='Número de celular'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='email',
            field=models.CharField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='matricula',
            field=models.CharField(max_length=13, unique=True, verbose_name='Matrícula do Estudante'),
        ),
    ]
