# Generated by Django 3.2.16 on 2022-11-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0005_auto_20221126_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='titulo',
            field=models.CharField(max_length=64, verbose_name='Título da atividade'),
        ),
    ]
