# Generated by Django 3.2.16 on 2022-11-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0006_alter_atividade_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='titulo',
            field=models.CharField(max_length=64, unique=True, verbose_name='Título da atividade'),
        ),
    ]
