# Generated by Django 3.2.16 on 2022-11-26 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0007_alter_atividade_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='em_grupo',
        ),
    ]
