# Generated by Django 3.2.16 on 2022-11-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0003_alter_recurso_descricao'),
        ('participante', '0008_remove_atividade_em_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='recursos',
            field=models.ManyToManyField(blank=True, to='organizacao.Recurso'),
        ),
    ]
