# Generated by Django 3.2.16 on 2022-11-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0011_alter_atividade_recursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formato_atividade',
            name='nome',
            field=models.CharField(max_length=64, unique=True, verbose_name='Formato da atividade'),
        ),
        migrations.AlterField(
            model_name='tipo_atividade',
            name='nome',
            field=models.CharField(max_length=64, unique=True, verbose_name='Tipo de atividade'),
        ),
    ]
