# Generated by Django 4.1.3 on 2022-12-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0013_remove_participante_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='email',
            field=models.CharField(max_length=254, verbose_name='Email'),
        ),
    ]
