# Generated by Django 3.2.13 on 2022-12-01 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0014_alter_participante_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='vinculo',
            field=models.CharField(choices=[('i', 'Interno'), ('e', 'Externo')], max_length=1, null=True, verbose_name='Vínculo institucional'),
        ),
    ]
