# Generated by Django 4.1.3 on 2022-12-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0016_alter_participante_vinculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(max_length=1028, verbose_name='Descrição da apresentação'),
        ),
    ]
